# Generated by Django 5.2.4 on 2025-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestido',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque:'),
        ),
    ]
