# Generated by Django 5.2.4 on 2025-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome do Produto:')),
                ('preco', models.CharField(max_length=10, verbose_name='Preço:')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes do Produto:')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque:')),
                ('cor', models.CharField(choices=[('AZ', 'Azul'), ('VM', 'Vermelho'), ('PR', 'Preto'), ('BR', 'Branco'), ('AM', 'Amarelo')], default='AZ', max_length=2, verbose_name='Cor:')),
                ('tamanho', models.CharField(choices=[('PP', 'Extra Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], default='M', max_length=2, verbose_name='Tamanho:')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto:')),
            ],
        ),
    ]
